### ISSUE TITLE
How to do testing?

### ISSUE THREAD

**Issue by WangLiwen1994** [parasmaharjan/DeepImageDenoising#1]
Hello. Thanks for sharing the code. I met a problem when I try to run your test code. 

Is the file "./chekpoint/EDSR/edsr_se_lrelu_ps_256_b_32_e6000.pth" stores the training model of your paper? I use the file "Pytorch_EDSR.py" to load the model, but the outputs are all noise? 

Could you please help me solve it?

**Comment by WangLiwen1994** [comment]
I have solved the problem by activating the SEBlock in the "common.py" file. Thanks again for sharing the code.

**Comment by Yingchi1998** [comment]
Hi, How to solove it? Could you tell some details?
